# Generated by Django 5.2 on 2025-05-03 18:17

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="更新日時"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        help_text="ユニーク注文番号", max_length=100, unique=True
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, help_text="合計金額", max_digits=10
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD", help_text="通貨コード", max_length=10
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        help_text="注文状態",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="更新日時"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        help_text="支払い方法種別（カード、PayPalなど）", max_length=50
                    ),
                ),
                ("details", models.JSONField(help_text="支払い情報詳細（暗号化保存）")),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, help_text="デフォルト支払い方法かどうか"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="ロール名称", max_length=50, unique=True
                    ),
                ),
                (
                    "permissions",
                    models.JSONField(
                        blank=True, default=list, help_text="権限リスト（JSON配列）"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="タグ名", max_length=100)),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL用一意スラッグ",
                        null=True,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="カテゴリ名", max_length=100)),
                ("slug", models.SlugField(help_text="URL用一意スラッグ", unique=True)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="作成日時"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="親カテゴリ",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="marketplace.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, help_text="単価", max_digits=10
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1, help_text="数量")),
                (
                    "order",
                    models.ForeignKey(
                        help_text="親注文",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="marketplace.order",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LicenseKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="ライセンスキー", max_length=255, unique=True
                    ),
                ),
                (
                    "issued_at",
                    models.DateTimeField(auto_now_add=True, help_text="発行日時"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(blank=True, help_text="有効期限", null=True),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        help_text="関連購入アイテム",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="licenses",
                        to="marketplace.orderitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_id",
                    models.CharField(help_text="外部決済ID", max_length=200),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="決済金額", max_digits=10
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD", help_text="通貨コード", max_length=10
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("succeeded", "Succeeded"), ("failed", "Failed")],
                        default="pending",
                        help_text="決済状態",
                        max_length=20,
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, help_text="支払完了日時", null=True
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        help_text="関連注文",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment",
                        to="marketplace.order",
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        help_text="使用した支払い方法",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="marketplace.paymentmethod",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="商品タイトル", max_length=200)),
                ("description", models.TextField(help_text="商品説明")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=0, help_text="販売価格", max_digits=10
                    ),
                ),
                (
                    "discount_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="割引価格",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending"),
                            ("published", "Published"),
                        ],
                        default="draft",
                        help_text="公開状態",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="更新日時"),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        help_text="紐づくカテゴリ",
                        related_name="products",
                        to="marketplace.category",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        help_text="紐づくタグ",
                        related_name="products",
                        to="marketplace.tag",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                help_text="注文商品",
                on_delete=django.db.models.deletion.CASCADE,
                to="marketplace.product",
            ),
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1, help_text="数量")),
                (
                    "cart",
                    models.ForeignKey(
                        help_text="親カート",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="marketplace.cart",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="カート商品",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="marketplace.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="アップロードファイル", upload_to="product_assets/"
                    ),
                ),
                (
                    "preview_image",
                    models.ImageField(
                        blank=True,
                        help_text="プレビュー画像",
                        null=True,
                        upload_to="product_previews/",
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("full_zip", "Full ZIP"),
                            ("thumbnail", "Thumbnail"),
                            ("preview_video", "Preview Video"),
                        ],
                        help_text="アセット種別",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="作成日時"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="関連商品",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="marketplace.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="一意のメールアドレスを使用します",
                        max_length=254,
                        unique=True,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="このユーザーが所属するグループ",
                        related_name="marketplace_user_set",
                        to="auth.group",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="このユーザーに割り当てられた権限",
                        related_name="marketplace_user_set",
                        to="auth.permission",
                    ),
                ),
            ],
            options={
                "verbose_name": "ユーザー",
                "verbose_name_plural": "ユーザー",
                "ordering": ["-date_joined"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.PositiveSmallIntegerField(help_text="評価点数(1-5)")),
                ("comment", models.TextField(blank=True, help_text="コメント内容")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="投稿日時"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="対象商品",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="marketplace.product",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        help_text="レビュー投稿者",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="marketplace.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(blank=True, help_text="表示名", max_length=100),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        help_text="プロフィール画像",
                        null=True,
                        upload_to="avatars/",
                    ),
                ),
                ("bio", models.TextField(blank=True, help_text="自己紹介文")),
                (
                    "website_url",
                    models.URLField(blank=True, help_text="ウェブサイトURL"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="参照先のユーザー",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="marketplace.user",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="seller",
            field=models.ForeignKey(
                blank=True,
                help_text="出品者ユーザー",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="marketplace.user",
            ),
        ),
        migrations.CreateModel(
            name="Preferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        default="en", help_text="表示言語コード", max_length=10
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="UTC", help_text="タイムゾーン", max_length=50
                    ),
                ),
                (
                    "email_notifications",
                    models.BooleanField(
                        default=True, help_text="メール通知を受け取るかどうか"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="参照先のユーザー",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to="marketplace.user",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="user",
            field=models.ForeignKey(
                help_text="支払い方法を持つユーザー",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_methods",
                to="marketplace.user",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="buyer",
            field=models.ForeignKey(
                help_text="購入者ユーザー",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="marketplace.user",
            ),
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(help_text="通知種別", max_length=50)),
                ("message", models.TextField(help_text="通知メッセージ")),
                ("is_read", models.BooleanField(default=False, help_text="既読フラグ")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="作成日時"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="通知受信者",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="marketplace.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DownloadHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "downloaded_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="ダウンロード日時"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(help_text="ダウンロード時IPアドレス"),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        help_text="ダウンロードアセット",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="downloads",
                        to="marketplace.productasset",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="ダウンロードユーザー",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="downloads",
                        to="marketplace.user",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cart",
            name="user",
            field=models.OneToOneField(
                help_text="カート所有者",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart",
                to="marketplace.user",
            ),
        ),
        migrations.CreateModel(
            name="BillingRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="請求金額", max_digits=10
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD", help_text="通貨コード", max_length=10
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, help_text="請求内容の説明", max_length=255
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="請求日時"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="請求対象のユーザー",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_records",
                        to="marketplace.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        help_text="住所種別（billing/shippingなど）", max_length=20
                    ),
                ),
                ("line1", models.CharField(help_text="住所行1", max_length=255)),
                (
                    "line2",
                    models.CharField(blank=True, help_text="住所行2", max_length=255),
                ),
                ("city", models.CharField(help_text="市区町村", max_length=100)),
                ("state", models.CharField(help_text="都道府県/州", max_length=100)),
                ("postal_code", models.CharField(help_text="郵便番号", max_length=20)),
                (
                    "country",
                    models.CharField(help_text="国コード (ISO2)", max_length=2),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, help_text="電話番号", max_length=20),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="住所情報を持つユーザー",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="marketplace.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="実行されたアクション内容", max_length=100
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(help_text="実行時のIPアドレス"),
                ),
                (
                    "user_agent",
                    models.CharField(
                        help_text="実行時のユーザーエージェント情報", max_length=255
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="アクション実行日時"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="アクションを実行したユーザー",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to="marketplace.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        help_text="付与されるロール",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_users",
                        to="marketplace.role",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="ロールを付与するユーザー",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_roles",
                        to="marketplace.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="作成日時"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="リスト所有者",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlist",
                        to="marketplace.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WishlistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "added_at",
                    models.DateTimeField(auto_now_add=True, help_text="追加日時"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="ウィッシュリスト商品",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="marketplace.product",
                    ),
                ),
                (
                    "wishlist",
                    models.ForeignKey(
                        help_text="親ウィッシュリスト",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="marketplace.wishlist",
                    ),
                ),
            ],
        ),
    ]
